/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as PartnersIndexRouteImport } from './routes/partners.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as PartnersIdRouteImport } from './routes/partners.$id'
import { Route as AdminVerifyRouteImport } from './routes/admin.verify'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIdRoute = PartnersIdRouteImport.update({
  id: '/partners/$id',
  path: '/partners/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/partners/$id': typeof PartnersIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/partners/$id': typeof PartnersIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/admin': typeof AdminIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/partners/$id': typeof PartnersIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/admin/documents'
    | '/admin/upload'
    | '/admin/verify'
    | '/partners/$id'
    | '/services/$id'
    | '/admin/'
    | '/partners/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin/documents'
    | '/admin/upload'
    | '/admin/verify'
    | '/partners/$id'
    | '/services/$id'
    | '/admin'
    | '/partners'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/admin/documents'
    | '/admin/upload'
    | '/admin/verify'
    | '/partners/$id'
    | '/services/$id'
    | '/admin/'
    | '/partners/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PartnersIdRoute: typeof PartnersIdRoute
  ServicesIdRoute: typeof ServicesIdRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$id': {
      id: '/partners/$id'
      path: '/partners/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof PartnersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminVerifyRoute: AdminVerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PartnersIdRoute: PartnersIdRoute,
  ServicesIdRoute: ServicesIdRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
