/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersIndexRouteImport } from './routes/partners.index'
import { Route as PartnersIdRouteImport } from './routes/partners.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIdRoute = PartnersIdRouteImport.update({
  id: '/partners/$id',
  path: '/partners/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/partners/$id': typeof PartnersIdRoute
  '/partners/': typeof PartnersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/partners/$id': typeof PartnersIdRoute
  '/partners': typeof PartnersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/partners/$id': typeof PartnersIdRoute
  '/partners/': typeof PartnersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/partners/$id' | '/partners/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/partners/$id' | '/partners'
  id: '__root__' | '/' | '/partners/$id' | '/partners/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PartnersIdRoute: typeof PartnersIdRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$id': {
      id: '/partners/$id'
      path: '/partners/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof PartnersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PartnersIdRoute: PartnersIdRoute,
  PartnersIndexRoute: PartnersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
